- id: "SQLi-001"
  name: "Basic SQL Injection"
  severity: "critical"
  pattern: "([';]|--|/\*).*(select|union|insert|update|delete|drop|exec)"
  locations: ["url", "body", "headers"]
  action: "block"

- id: "SQLi-002"
  name: "Time-Based Blind SQLi"
  severity: "high"
  pattern: "(sleep\(\d+\)|benchmark\(\d+,.+\)|pg_sleep\(\d+\))"
  locations: ["body", "query"]
  action: "block"