version: '3.8'

services:
  waf:
    build: .
    ports:
      - "8080:8080"  # Proxy port
      - "8000:8000"  # API port
    volumes:
      - ./config:/app/config
      - ./logs:/var/log/redhunter
    environment:
      - LOG_LEVEL=info

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata: